### ISSUE TITLE
The images are not visible in the AnnLoader tutorials.

### ISSUE THREAD

**Issue by Koncopd** [theislab/anndata-tutorials#6]
The images in _static are visible here
https://github.com/theislab/anndata-tutorials/blob/master/AnnLoader.ipynb
https://github.com/theislab/anndata-tutorials/blob/master/pytorch-multi-file.ipynb
But still not visible here
https://anndata-tutorials.readthedocs.io/en/latest/AnnLoader.html
https://anndata-tutorials.readthedocs.io/en/latest/pytorch-multi-file.html

**Comment by falexwolf** [comment]
Fixed it here: https://github.com/theislab/anndata-tutorials/pull/7!
